aluno = input("Digite o nome do aluno: ")
periodo_corrente = input("Digite o período corrente: ")
ira = float(input("Digite o IRA(Indice de rendimento academico):"))
laurea = bool(input("Informe se você é o aluno laureado(a) da turma: (True = Sim /False = Não): "))
print(type(aluno))
print(type(periodo_corrente))
print(type(ira))
print(type(laurea))
